// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3LYmJrMZfaTshiNjvm3ZAD771y-Xn5j8',
    appId: '1:1032051706704:web:ff5069602394c0148d7a55',
    messagingSenderId: '1032051706704',
    projectId: 'aqary-73d78',
    authDomain: 'aqary-73d78.firebaseapp.com',
    storageBucket: 'aqary-73d78.appspot.com',
    measurementId: 'G-DVJ3SL94CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcqpMNFwRJUOr8DyUADsLQBd8G2ZKE_Gk',
    appId: '1:1032051706704:android:109c8f8d1c8a54c98d7a55',
    messagingSenderId: '1032051706704',
    projectId: 'aqary-73d78',
    storageBucket: 'aqary-73d78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD1DNdow46OiOnjxtn2Vjc12slhCqyAV8',
    appId: '1:1032051706704:ios:bcc6d978d851c95b8d7a55',
    messagingSenderId: '1032051706704',
    projectId: 'aqary-73d78',
    storageBucket: 'aqary-73d78.appspot.com',
    iosBundleId: 'com.example.aqary',
  );
}
